### ISSUE TITLE
need support for advanced smelter

### ISSUE THREAD

**Issue by CharlesChou73** [wokdok/AddAmountOfRecipePer1min#3]
If you are still maintain the mod, I'd like it can support the newly added advanced smelter, which has double productivity compared with ordinary smelter.

It's a convenient mod, thanks for developing it.

**Comment by enriquein** [comment]
Added this to my fork of this mod: https://dsp.thunderstore.io/package/enriquein/AddAmountOfRecipePer1minContinued/

**Comment by CharlesChou73** [comment]
> Added this to my fork of this mod: https://dsp.thunderstore.io/package/enriquein/AddAmountOfRecipePer1minContinued/

Got it. Thanks very much for your work!

**Comment by CharlesChou73** [comment]
> Added this to my fork of this mod: https://dsp.thunderstore.io/package/enriquein/AddAmountOfRecipePer1minContinued/

Didn't find Issue tab in your forked peoject, so I write it here. 

Switching the displayed speed among diffirent structure level is a good idea, but it's a bit of annoying that every time I want to check productivity in mk3, I have to press Alt. Usually speaking, mk3 is the most used level.

So here are some methods to improve it:

Easiest, set mk3 as the default displaying level.

A little bit harder, add a config file to set the default level.

More harder but convenient, record the level that user checked last time, set it as the default level.

Hardest but perfect, add a combo box somewhere, maybe in the replicator panel, allowing user to select the default level.

Thanks again.

**Comment by enriquein** [comment]
Thanks for letting me know about the missing issues tab. I fixed that. Could you please close this issue here and create it there instead? 

I don't agree that MK3 should be the default display level, and seeing as different people have different preferences for this I think your idea of making it a configuration is the ideal way to go. I'll make some time this week to add this to the next release.
